Banking Operations/Controllers/BankingController.cs
using Banking_Operations.Data;
using Banking_Operations.Interfaces;
using Banking_Operations.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Banking_Operations.Controllers
{
    public class BankingController : Controller
    {
        private IBankServicesRepository _repository;
        private UserManager<Client> _clientManager;
        public BankingController(IBankServicesRepository repository, UserManager<Client> clientManager) 
        {
            _clientManager = clientManager;
            _repository = repository;
        }

        public async Task<IActionResult> Index()
        {
            Client client = await _clientManager.FindByNameAsync(User.Identity.Name);
            IEnumerable<BankService> bankServices = await _repository.GetByClientIdAsync(client.Id);
            return View(bankServices);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(BankingModel bankingModel)
        {
            if (!ModelState.IsValid)
            {
                return View(bankingModel);
            }

            Client client = await _clientManager.FindByNameAsync(User.Identity.Name);

            BankService bankService = new BankService
            {
                BankServiceName = bankingModel.BankServiceName,
                TermOfRendering = bankingModel.TermOfRendering,
                ComissionType = bankingModel.ComissionType,
                Debt = bankingModel.Debt,
                BankServiceStatus = false,
                ClientId = client.Id
            };
            _repository.Add(bankService);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(BankService bankService)
        {
            BankService newBankService = await _repository.GetByIdAsync(bankService.Id);

            BankingModel bankingModel = new BankingModel
            {
                ServiceID = newBankService.Id,
                BankServiceName = newBankService.BankServiceName,
                TermOfRendering = newBankService.TermOfRendering,
                ComissionType = newBankService.ComissionType,
                Debt = newBankService.Debt,
                ClientId = newBankService.ClientId
            }; 
            return View(bankingModel);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(BankService bankService)
        {
            BankService newBankService = await _repository.GetByIdAsync(bankService.Id);

            BankingModel bankingModel = new BankingModel
            {
                ServiceID = newBankService.Id,
                BankServiceName = newBankService.BankServiceName,
                TermOfRendering = newBankService.TermOfRendering,
                ComissionType = newBankService.ComissionType,
                Debt = newBankService.Debt,
                ClientId = newBankService.ClientId,
                BankServiceState = newBankService.BankServiceStatus
            };
            return View(bankingModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(BankingModel bankingModel)
        {
            Client client = await _clientManager.FindByNameAsync(User.Identity.Name);
            var bankService = new BankService
            {
                Id = bankingModel.ServiceID,
                BankServiceName = bankingModel.BankServiceName,
                TermOfRendering = bankingModel.TermOfRendering,
                ComissionType = bankingModel.ComissionType,
                Debt = bankingModel.Debt,
                BankServiceStatus = Convert.ToBoolean(bankingModel.BankServiceState),
                ClientId = client.Id
            };
            _repository.Update(bankService);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Index");
            }
            var bankService = await _repository.GetByIdAsync(id);
            _repository.Delete(bankService);
            return RedirectToAction("Index");
        }
    }
}

Banking Operations/Controllers/ContactsController.cs
using Banking_Operations.Models;
using Microsoft.AspNetCore.Mvc;

namespace Banking_Operations.Controllers
{
    public class ContactsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        
        [HttpPost]
        public IActionResult Check(ContactsModel CM)
        {
            
            if (ModelState.IsValid)
            {
                return Redirect("/");
            }
            return View("Index");
        
    }
        
    }
}

Banking Operations/Views/Shared/_Layout.cshtml
@using Banking_Operations.Data
﻿@using Microsoft.AspNetCore.Identity
@inject SignInManager<Client> SignInManager

<!DOCTYPE html>
<html lang="en" class="h-100">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />
    <title>@ViewData["Title"] - Banking_Operations</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/test.styles.css" asp-append-version="true" />
</head>
<body class="d-flex h-100 text-center text-white bg-dark overflow-hidden">
    <div class="d-flex w-100 h-100 p-3 mx-auto flex-column">
        <header class="mb-auto cover-container">
            <div>
            <nav class="nav nav-masthead justify-content-center float-md-end">
                <div class="container-fluid gx-5">
                    <a aria-current="page" class="navbar-brand float-md-start mb-0" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                            @*<a class="nav-link " asp-area="" asp-controller="Contacts" asp-action="Index">Свяжитесь с нами!</a>*@
                            @if (!SignInManager.IsSignedIn(User))
                            {
                                    <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Login">Войти</a>

                                    <a class="nav-link " asp-area="" asp-controller="Account" asp-action="Register">Зарегистрироваться</a>
                            }
                            else
                            {
                                    <a class="nav-link" asp-area="" asp-controller="Banking" asp-action="Index">Услуги</a>
                                <form asp-controller="Account" asp-action="Logout">
                                    <button class="btn btn-outline-danger mx-3 my-sm-0">Выйти</button>
                                </form>

                            }
                    </div>
                </div>
            </nav>
            </div>
        </header>

        <div class="container d-flex justify-content-center align-items-center h-100">
        <main role="main" class="px-3">
            @RenderBody()
        </main>
        </div>

    <footer class="mt-auto footer text-white-5">
        <div class="container">
            &copy; 2023 - Banking Operations - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>